<?php $currencyFlag = unserialize(Mage::getStoreConfig('currency/options/currencyflag', "")); ?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-system-currency"><?php echo $this->getHeader() ?></h3></td>
            <td class="form-buttons">
                <?php
                    echo $this->getSaveButtonHtml();
                ?>
            </td>
        </tr>
    </table>
</div>
<?php $this->getCurrencySymbolsData();?>
<form id="currency_symbols_form" action="<?php echo $this->getFormActionUrl() ?>" method="post" enctype="multipart/form-data">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />

    <div class="entry-edit">
        <div class="fieldset fieldset-wide">
            <div class="grid">
                <div class="hor-scroll">
                    <table cellspacing="0" class="data table-cat-img-sizes">
                        <colgroup>
                            <col width="15%"/>
                            <col />
                            <col width="25%" />
                        </colgroup>
                        <thead>
                            <tr class="headings">
                                <th><span class="nobr"><span class="not-sort"><?php echo $this->__('Currency'); ?></span></span></th>
                                <th><span class="nobr"><span class="not-sort"><?php echo $this->__('Symbol'); ?><span class="required"><em>*</em></span></span></span></th>
                                <th><span class="nobr"><span class="not-sort"><?php echo $this->__('Flag'); ?></span></span></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->getCurrencySymbolsData() as $code => $data): ?>
                            <tr>
                                <td class="label">
                                <label for="custom_currency_symbol<?php echo $code; ?>"><?php echo $code; ?> (<?php echo $data['displayName']; ?>)</label>
                                </td>
                                <td class="value">
                                    <input id="custom_currency_symbol<?php echo $code; ?>" class=" required-entry input-text" type="text" value="<?php echo Mage::helper('core')->quoteEscape($data['displaySymbol']); ?>"<?php echo $data['inherited'] ? ' disabled="disabled"' : '';?> name="custom_currency_symbol[<?php echo $code; ?>]">
                                    &nbsp; <input id="custom_currency_symbol_inherit<?php echo $code; ?>" class="checkbox config-inherit" type="checkbox" onclick="toggleUseDefault(<?php echo '\'' . $code . '\',\'' . Mage::helper('core')->quoteEscape($data['parentSymbol'], true) . '\''; ?>)"<?php echo $data['inherited'] ? ' checked="checked"' : ''; ?> value="1" name="inherit_custom_currency_symbol[<?php echo $code; ?>]">
                                    <label class="inherit" title="" for="custom_currency_symbol_inherit<?php echo $code; ?>"><?php echo $this->getInheritText(); ?></label>
                                </td>
                                <td class="value">
                                    <?php if (isset($currencyFlag[$code])): ?>
                                        <img src="<?php echo Mage::getBaseUrl('media') . $currencyFlag[$code] ?>" alt="<?php echo $code ?>">
                                    <?php endif; ?>
                                    <input type="file" name="<?php echo $code ?>">
                                    <input type="checkbox" name="delete_currency_flag[<?php echo $code ?>]" value="1" id="delete_currency_flag_<?php echo $code ?>">
                                    <label for="delete_currency_flag_<?php echo $code ?>"><?php echo $this->__('Delete Flag') ?></label>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    var currencySymbolsForm = new varienForm('currency_symbols_form');

    function toggleUseDefault(code, value)
    {
        checkbox = $('custom_currency_symbol_inherit'+code);
        input = $('custom_currency_symbol'+code);
        if (checkbox.checked) {
            input.value = value;
            input.disabled = true;
        } else {
            input.disabled = false;
        }
    }
</script>

