<?php if($this->getCurrencyCount()>1):
    $currencyFlags = unserialize(Mage::getStoreConfig('currency/options/currencyflag', ""));
    $currentCurrency = $this->getCurrentCurrencyCode();
?>
<div class="currency-switcher">
    <div class="current-currency">
        <?php if (isset($currencyFlags[$currentCurrency])): ?>
            <img src="<?php echo Mage::getBaseUrl('media') . $currencyFlags[$currentCurrency] ?>" alt="<?php echo $currentCurrency ?>">
        <?php endif; ?>
        <span class="symbol"><?php echo Mage::app()->getLocale()->currency($currentCurrency)->getSymbol() ?></span>
        <span class="name"><?php echo Mage::app()->getLocale()->currency($currentCurrency)->getName() ?></span>
        <span class="code"><?php echo $currentCurrency ?></span>
    </div>
    <div class="currencies">
    <?php foreach ($this->getCurrencies() as $code => $name): ?>
        <a href="<?php echo $this->getSwitchCurrencyUrl($code) ?>" <?php if($code == $currentCurrency) echo 'class="currency-switcher-current"' ?>>
            <?php if (isset($currencyFlags[$code])): ?>
                <img src="<?php echo Mage::getBaseUrl('media') . $currencyFlags[$code] ?>" alt="<?php echo $code ?>">
            <?php endif; ?>
            <span class="symbol"><?php echo Mage::app()->getLocale()->currency($code)->getSymbol() ?></span>
            <span class="name"><?php echo $name ?></span>
            <span class="code"><?php echo $code ?></span>
        </a>
    <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
